# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=T6UWP3FDTURFSZIK
sasl.password=CZMVZzG0bW7BvQusacHMjXHFLYjaZ3YoOqMiuADlb5KuqmVLEEvVnAC7YDcYOy7I

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-nodejs-client-2af426c2-2410-4a4c-b5a0-3e79f93bf2a7
